server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql:///foolish?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  redis:
    host: 106.54.243.172
    port: 6379

mybatis-plus:
  typeEnumsPackage: com.foolish.springcache.enums
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.foolish.springcache.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



